name: slide_indexed_stack
description: A IndexedStack with slide in and out animation
version: 0.0.1
repository: https://github.com/blklmn345/slide_indexed_stack

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
